/*
 * Sales Catalogue Service API
 *
 * This API is for Sales Catalogue Service 
 *
 * OpenAPI spec version: 1
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;
using UKHO.SalesCatalogueStub.Api.Attributes;
using UKHO.SalesCatalogueStub.Api.Models;

namespace UKHO.SalesCatalogueStub.Api.Controllers
{
    /// <summary>
    /// </summary>
    [ApiController]
    public class ExchangeServiceApiController : ControllerBase
    {
        /// <summary>
        ///     Get the latest, releasable versions for requested products or changes to requested products since a date
        /// </summary>
        /// <param name="productType">The type of product         </param>
        /// <param name="body">
        ///     The JSON body containing product identifiers.
        /// </param>
        /// <param name="sinceDateTime">
        ///     The date and time from which changes are requested. Any changes since the date will be
        ///     returned.
        /// </param>
        /// <response code="200">A JSON body of product objects</response>
        /// <response code="304">Not modified.</response>
        /// <response code="400">Bad request.</response>
        /// <response code="401">Unauthorised.</response>
        /// <response code="403">Forbidden.</response>
        /// <response code="404">Not found.</response>
        /// <response code="406">Not acceptable.</response>
        /// <response code="500">Internal Server Error.</response>
        [HttpPost]
        [Route("/v1/productData/{productType}/products/productIdentifiers")]
        //[Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("PostProductIdentifiers")]
        [SwaggerResponse(200, type: typeof(Products), description: "A JSON body of product objects")]
        [SwaggerResponse(400, type: typeof(ErrorDescription), description: "Bad request.")]
        [SwaggerResponse(404, type: typeof(DefaultErrorResponse), description: "Not found.")]
        [SwaggerResponse(406, type: typeof(DefaultErrorResponse), description: "Not acceptable.")]
        [SwaggerResponse(500, type: typeof(DefaultErrorResponse), description: "Internal Server Error.")]
        public virtual IActionResult PostProductIdentifiers([FromRoute] [Required] string productType,
            [FromBody] List<string> body, [FromQuery] DateTime? sinceDateTime)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Products));

            //TODO: Uncomment the next line to return response 304 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(304);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorDescription));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(DefaultErrorResponse));

            //TODO: Uncomment the next line to return response 406 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(406, default(DefaultErrorResponse));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(DefaultErrorResponse));
            string exampleJson = null;
            exampleJson =
                "{\n  \"productName\" : \"AU895561\",\n  \"editionNumber\" : 4,\n  \"updateNumber\" : [ 5, 6, 7 ]\n}";

            var example = exampleJson != null
                ? JsonConvert.DeserializeObject<Products>(exampleJson)
                : default; //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        ///     Get the latest, releasable versions of requested products since a specified version
        /// </summary>
        /// <param name="productType">The type of product         </param>
        /// <param name="body">
        ///     The JSON body containing product versions.
        /// </param>
        /// <response code="200">A JSON body of product objects</response>
        /// <response code="304">Not modified.</response>
        /// <response code="400">Bad request.</response>
        /// <response code="401">Unauthorised.</response>
        /// <response code="403">Forbidden.</response>
        /// <response code="404">Not found.</response>
        /// <response code="406">Not acceptable.</response>
        /// <response code="500">Internal Server Error.</response>
        [HttpPost]
        [Route("/v1/productData/{productType}/products/productVersions")]
        //[Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("PostProductVersions")]
        [SwaggerResponse(200, type: typeof(Products), description: "A JSON body of product objects")]
        [SwaggerResponse(400, type: typeof(ErrorDescription), description: "Bad request.")]
        [SwaggerResponse(404, type: typeof(DefaultErrorResponse), description: "Not found.")]
        [SwaggerResponse(406, type: typeof(DefaultErrorResponse), description: "Not acceptable.")]
        [SwaggerResponse(500, type: typeof(DefaultErrorResponse), description: "Internal Server Error.")]
        public virtual IActionResult PostProductVersions([FromRoute] [Required] string productType,
            [FromBody] List<ProductVersionsInner> body)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Products));

            //TODO: Uncomment the next line to return response 304 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(304);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorDescription));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(DefaultErrorResponse));

            //TODO: Uncomment the next line to return response 406 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(406, default(DefaultErrorResponse));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(DefaultErrorResponse));
            string exampleJson = null;
            exampleJson =
                "{\n  \"productName\" : \"AU895561\",\n  \"editionNumber\" : 4,\n  \"updateNumber\" : [ 5, 6, 7 ]\n}";

            var example = exampleJson != null
                ? JsonConvert.DeserializeObject<Products>(exampleJson)
                : default; //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}